baseURL = 'https://chris-beischl.github.io'
languageCode = 'en-us'
title = "Chris's Computer Science and Maths Blog"

[module]
[[module.imports]]
path = "github.com/tomfran/typo"

[params]
# Meta description
description = "This is my personal geek blog"  

theme = 'auto' 
colorpalette = 'catpuccin'
hiddenHeader = true 

homeIntroTitle = "Hi!"
homeIntroContent = """
Hey, I'm Chris! I am currently finishing my Masters degree in Data Engineering
and Analytics and the best part about me is, that I can easily get excited over 
the most trivial things.
I'm currently focusing on machine learning, more specifically vision
transformers (ViT), however I am also interested in topics from maths,
algorithms and data science. 
"""

# Collection to display on home: 
homeCollectionTitle = 'Posts' 
homeCollection = 'posts'

# Breadcrumbs: 
breadcrumbs = false

# Main menu pages: 
[[params.menu]]
name = "home" 
url = "/"

[[params.menu]]
name = "posts" 
url = "/posts"

[[params.meuu]]
name = "about" 
url = "/about" 

# Syntax highlight on code blocks 
[markup] 
[markup.highlight] 
style = 'algol'
